var NS = 'http://www.w3.org/2000/svg';

//SVG
var UNITS = 'mm';
var DOT_RADIUS = 10;
var SVG_SIZE = 100;
var GAP_WIDTH = 2;
var ARC_WIDTH = 18;
var ARC_RADIUS = DOT_RADIUS + GAP_WIDTH + ARC_WIDTH/2;
var CLIP_PATH_ID = 0;
var EMPTY_ARC_HUE = 0;
var EMPTY_ARC_SATURATION = '0%';
var EMPTY_ARC_LIGHTNESS = '40%';
var EMPTY_ARC_ALPHA = .5;
var FILL_ARC_LIGHTNESS = '30%';
var FILL_ARC_SATURATION = '100%';
var FILL_ARC_ALPHA = '.9';
var INDICATOR_ARC_LIGHTNESS = '50%';
var INDICATOR_ARC_SATURATION = '100%';
var INDICATOR_ARC_ALPHA = '1';
var INDICATOR_WIDTH = 2;
var TAP_TIMEOUT = 200;
var DRAG_BOX_SIZE = 10; //in mm
var HOLD_EFFECT_VIBRATE_TIME = 100;
var CONNECTION_WIDTH = 2;
var CONNECTION_SVG_PADDING = 5;
var DOT_NAME_SIZE = 7;
var MENU_BUTTON_SIZE = 10;
var DOT_LIGHTNESS = "30%";
var DOT_SATURATION = "100%";
var DOT_ALPHA = "1";
var CONNECTION_LIGHTNESS = "30%";

//physics
var DOT_PHYSICS_RADIUS = DOT_RADIUS + ARC_WIDTH/2 + GAP_WIDTH;
var GRID_SIZE = DOT_PHYSICS_RADIUS*1.4;
var CONTINUOUS_PHYSICS = false;
var nodeArray = [];

var DOT_CONTAINER = document.getElementById('workspace');
var DOT_CONTAINER_WRAPPER = document.getElementById('workspaceWrapper');

//Undo/Redo
var MAX_UNDO = 20;
var MAX_REDO = 20;